name = "server"
main = "src/index.ts"
compatibility_date = "2024-09-27"
compatibility_flags = [ "nodejs_compat" ]
[observability]
enabled = true
# [vars]
# MY_VAR = "my-variable"
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNTIyMGQzZDMtZGZjMC00Y2M5LWFlZWMtNWQzOTM3OTIwYTU4IiwidGVuYW50X2lkIjoiMTUwZDJhZjdkNDBkMjkzNjBiZGE2ZmIwZjBlYzcwMmI0ZDQ0OTQ4NzA4N2FiZDU1NWRmNzI0ZTU0MzFjZjNiZSIsImludGVybmFsX3NlY3JldCI6IjBiZTNkYTMyLWExYjEtNDAzYS1hNTQ2LWIyY2Q2OTBhMWZiMyJ9.5R8e2bXfVq0kV90qbwIwrdAjqoKJMjNm-4NHzN761_0"
DIRECT_DATABASE_URL="mongodb+srv://ktandon2004:itsmagic2004@cluster0.qcv8vkf.mongodb.net/nestMate"
JWT_SECRET="xc21"
CLOUDINARY_CLOUD_NAME="dwfjllapi"
CLOUDINARY_API_KEY="969363628261119"
CLOUDINARY_API_SECRET="rtnxaG1QjfqGK54cXtiJlOWsU1g"


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
